const $=s=>document.querySelector(s), view=$('#view');
const state={route:'home',params:{},editing:null,wake:null,keepScreen:false};
let db;
const icons=['🍲','🥘','🥗','🍰','🧁','🥖','🍳','🥤','🍝','🍪','🍕','🥣'];
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('pancia-gotuje-db',1);r.onupgradeneeded=e=>{db=e.target.result;db.createObjectStore('recipes',{keyPath:'id'});db.createObjectStore('categories',{keyPath:'id'});db.createObjectStore('settings',{keyPath:'key'})};r.onsuccess=e=>{db=e.target.result;resolve()};r.onerror=()=>reject(r.error)})}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function getAll(name){return new Promise((res,rej)=>{const r=store(name).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function put(name,v){return new Promise((res,rej)=>{const r=store(name,'readwrite').put(v);r.onsuccess=()=>res(v);r.onerror=()=>rej(r.error)})}
function del(name,k){return new Promise((res,rej)=>{const r=store(name,'readwrite').delete(k);r.onsuccess=res;r.onerror=()=>rej(r.error)})}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
async function cats(){return (await getAll('categories')).sort((a,b)=>a.order-b.order)}
async function recipes(){return await getAll('recipes')}
function route(r,params={}){state.route=r;state.params=params;render()}
function navActive(){document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.route===state.route));$('.bottom-nav .add-nav').classList.toggle('active',state.route==='add')}
function setHeader(title,sub='',back=false,action=''){ $('#pageTitle').textContent=title;$('#pageSubtitle').textContent=sub;$('#backBtn').classList.toggle('hidden',!back);$('#headerAction').classList.toggle('hidden',!action);$('#headerAction').textContent=action; }
function fmtMeta(r){let a=[];if(r.prepTime)a.push('◷ '+r.prepTime+' min');if(r.cookTime)a.push('♨ '+r.cookTime+' min '+(r.cookType||''));if(r.servings)a.push('◉ '+r.servings+' porcji');return a.map(x=>`<span>${x}</span>`).join('')}
function thumb(r){return r.photo?`<img class="recipe-thumb" src="${r.photo}" alt="">`:`<div class="recipe-thumb" style="display:grid;place-items:center;font-size:30px">🍽️</div>`}
async function render(){navActive();$('.bottom-nav').style.display=['detail','edit'].includes(state.route)?'none':'flex';
 if(state.route==='home'){setHeader('Pańcia gotuje','Tu mieszkają najlepsze przepisy');const [c,rs]=await Promise.all([cats(),recipes()]);view.innerHTML=`<div class="section-title"><h2>Kategorie</h2><button id="allCats">Zobacz wszystkie</button></div><div class="category-grid">${c.length?c.slice(0,6).map((x,i)=>`<button class="category-card" data-cat="${x.id}"><span>${x.icon||icons[i%icons.length]}</span><b>${esc(x.name)}</b><small>${rs.filter(r=>r.categoryId===x.id).length} przepisów</small></button>`).join(''):`<div class="empty" style="grid-column:1/-1">Dodaj swoją pierwszą kategorię w Menu → Kategorie.</div>`}</div><div class="section-title"><h2>Najnowsze przepisy</h2><button id="allRecipes">Zobacz wszystkie</button></div><div class="recipe-list">${rs.sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,5).map(card).join('')||'<div class="empty">Jeszcze tu pusto. Dodaj pierwszy przepis! 👩‍🍳</div>'}</div>`;
 $('#homeSearch').oninput=e=>{if(e.target.value.trim())route('search',{q:e.target.value})};document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>route('list',{cat:b.dataset.cat}));$('#allCats').onclick=()=>route('categories');$('#allRecipes').onclick=()=>route('list');bindCards();return}
 if(state.route==='categories'){setHeader('Kategorie','Twoje kulinarne półki');const [c,rs]=await Promise.all([cats(),recipes()]);view.innerHTML=`<div class="section-title"><h2>Wybierz kategorię</h2><button id="manageCats">✎ Edytuj</button></div><div class="category-grid">${c.map((x,i)=>`<button class="category-card" data-cat="${x.id}"><span>${x.icon||icons[i%icons.length]}</span><b>${esc(x.name)}</b><small>${rs.filter(r=>r.categoryId===x.id).length} przepisów</small></button>`).join('')||'<div class="empty">Nie masz jeszcze kategorii.</div>'}</div>`;$('#manageCats').onclick=()=>route('settings',{section:'cats'});document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>route('list',{cat:b.dataset.cat}));return}
 if(state.route==='list'){const [c,rs]=await Promise.all([cats(),recipes()]);const filtered=state.params.cat?rs.filter(r=>r.categoryId===state.params.cat):rs;const name=state.params.cat?(c.find(x=>x.id===state.params.cat)?.name||'Przepisy'):'Wszystkie przepisy';setHeader(name,filtered.length+' przepisów',true);view.innerHTML=`<div class="tabs"><button class="selected">${esc(name)}</button>${c.filter(x=>x.id!==state.params.cat).map(x=>`<button data-switch-cat="${x.id}">${esc(x.name)}</button>`).join('')}</div><div class="recipe-list" style="margin-top:14px">${filtered.sort((a,b)=>a.title.localeCompare(b.title,'pl')).map(card).join('')||'<div class="empty">Brak przepisów w tej kategorii.</div>'}</div>`;document.querySelectorAll('[data-switch-cat]').forEach(b=>b.onclick=()=>route('list',{cat:b.dataset.switchCat}));bindCards();return}
 if(state.route==='search'){setHeader('Wyszukiwanie','Znajdź swój przepis');const rs=await recipes(),q=state.params.q||'';const filtered=q?rs.filter(r=>r.title.toLowerCase().includes(q.toLowerCase())):rs;view.innerHTML=`<div class="search-box">⌕ <input id="searchInput" autofocus value="${esc(q)}" placeholder="Wpisz nazwę przepisu..."></div><p class="muted">Wyniki (${filtered.length})</p><div class="recipe-list">${filtered.map(card).join('')||'<div class="empty">Nie znaleziono żadnego przepisu.</div>'}</div>`;$('#searchInput').oninput=e=>route('search',{q:e.target.value});bindCards();return}
 if(state.route==='detail'){const r=(await recipes()).find(x=>x.id===state.params.id);if(!r){route('home');return}setHeader('Szczegóły przepisu','',true,'✎');$('#headerAction').onclick=()=>route('edit',{id:r.id});view.innerHTML=`${r.photo?`<img class="detail-photo" src="${r.photo}" alt="${esc(r.title)}">`:''}<div class="detail-head"><h2>${esc(r.title)}</h2><div class="meta">${fmtMeta(r)}</div></div><div class="detail-actions"><button class="primary" id="editRecipe">✎ Edytuj przepis</button><button class="danger" id="deleteRecipe">Usuń</button></div><section class="detail-section"><h3>Składniki</h3><ul class="ingredients">${r.ingredients.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></section><section class="detail-section"><h3>Przygotowanie</h3><ol class="steps">${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section>`;$('#editRecipe').onclick=()=>route('edit',{id:r.id});$('#deleteRecipe').onclick=async()=>{if(confirm('Usunąć ten przepis?')){await del('recipes',r.id);toast('Przepis usunięty');route('home')}};return}
 if(['add','edit'].includes(state.route)){const rs=await recipes(),c=await cats();const r=state.route==='edit'?rs.find(x=>x.id===state.params.id):{id:uid(),title:'',categoryId:c[0]?.id||'',prepTime:'',cookTime:'',cookType:'pieczenia',servings:'',ingredients:[''],steps:[''],photo:'',updatedAt:Date.now()};state.editing=r;setHeader(state.route==='add'?'Dodaj przepis':'Edytuj przepis','',state.route==='edit');view.innerHTML=formHTML(r,c);bindForm(r);return}
 if(state.route==='settings'){setHeader('Menu','Twoja książka kucharska');const c=await cats();view.innerHTML=`<div class="settings-card"><div class="switch"><div><b>Nie wygaszaj ekranu</b><p class="muted">Podczas używania aplikacji</p></div><input id="wake" type="checkbox" ${state.keepScreen?'checked':''}></div></div><div class="settings-card"><h3>Kategorie</h3><p class="muted">Dodawaj, zmieniaj nazwy i kolejność kategorii.</p><div class="reorder-list" id="catList">${c.map(x=>`<div class="category-row" draggable="true" data-id="${x.id}"><span class="handle">☷</span><input value="${esc(x.name)}"><button class="mini-btn delete-cat">×</button></div>`).join('')}</div><button class="secondary" id="addCat">＋ Dodaj kategorię</button><button class="primary" id="saveCats">Zapisz kategorie</button></div><div class="settings-card"><h3>Kopia zapasowa</h3><p class="muted">Eksportuj wszystkie przepisy i kategorie do jednego pliku JSON.</p><button class="primary" id="export">⇩ Eksportuj kopię</button></div><div class="settings-card"><h3>O aplikacji</h3><p class="muted">Pańcia gotuje • prywatna książka kucharska działająca lokalnie.</p></div>`;bindSettings();return}
}
function card(r){return `<article class="recipe-card" data-recipe="${r.id}">${thumb(r)}<div class="recipe-info"><h3>${esc(r.title)}</h3><div class="meta">${fmtMeta(r)}</div><div style="margin-top:8px"><span class="chip">${esc(r.cookType||'przepis')}</span></div></div></article>`}
function bindCards(){document.querySelectorAll('[data-recipe]').forEach(x=>x.onclick=()=>route('detail',{id:x.dataset.recipe}))}
function formHTML(r,c){return `<div class="form-card"><div class="photo-picker" id="photoBox">${r.photo?`<img src="${r.photo}">`:`<div>📷<br><b>Dodaj zdjęcie potrawy</b><br><small>z aparatu lub galerii</small></div>`}</div><div class="picker-buttons"><button class="secondary" id="cameraBtn">Zrób zdjęcie</button><button class="secondary" id="galleryBtn">Wybierz z galerii</button></div></div><div class="form-card"><div class="field"><label>Nazwa przepisu</label><input id="title" value="${esc(r.title)}" placeholder="np. Sernik nowojorski"></div><div class="field"><label>Kategoria</label><select id="category"><option value="">Wybierz kategorię</option>${c.map(x=>`<option value="${x.id}" ${x.id===r.categoryId?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="inline-row"><div class="field"><label>Czas przygotowania (min)</label><input id="prepTime" type="number" min="0" value="${esc(r.prepTime)}"></div><div class="field"><label>Liczba porcji</label><input id="servings" type="number" min="1" value="${esc(r.servings)}"></div></div><div class="inline-row"><div class="field"><label>Rodzaj obróbki</label><select id="cookType"><option value="pieczenia">Pieczenie</option><option value="gotowania">Gotowanie</option><option value="smażenia">Smażenie</option></select></div><div class="field"><label>Czas obróbki (min)</label><input id="cookTime" type="number" min="0" value="${esc(r.cookTime)}"></div></div></div><div class="form-card"><h3>Składniki</h3><div id="ingredients">${r.ingredients.map((x,i)=>`<div class="ingredient-row"><input value="${esc(x)}" placeholder="np. 200 g mąki"><button class="mini-btn removeIng">×</button></div>`).join('')}</div><button class="secondary" id="addIng">＋ Dodaj składnik</button></div><div class="form-card"><h3>Przygotowanie</h3><div id="steps">${r.steps.map((x,i)=>`<div class="step-row"><textarea placeholder="Opisz kolejny krok">${esc(x)}</textarea><button class="mini-btn removeStep">×</button></div>`).join('')}</div><button class="secondary" id="addStep">＋ Dodaj krok</button></div><button class="primary" style="width:100%" id="saveRecipe">Zapisz przepis</button>`}
function bindForm(r){$('#cookType').value=r.cookType||'pieczenia';const addIng=()=>{$('#ingredients').insertAdjacentHTML('beforeend','<div class="ingredient-row"><input placeholder="np. 200 g mąki"><button class="mini-btn removeIng">×</button></div>');bindRemovers()};const addStep=()=>{$('#steps').insertAdjacentHTML('beforeend','<div class="step-row"><textarea placeholder="Opisz kolejny krok"></textarea><button class="mini-btn removeStep">×</button></div>');bindRemovers()};function bindRemovers(){document.querySelectorAll('.removeIng').forEach(b=>b.onclick=()=>b.parentElement.remove());document.querySelectorAll('.removeStep').forEach(b=>b.onclick=()=>b.parentElement.remove())}bindRemovers();$('#addIng').onclick=addIng;$('#addStep').onclick=addStep;$('#cameraBtn').onclick=()=>{$('#cameraInput').click();state.photoTarget=r};$('#galleryBtn').onclick=()=>{$('#galleryInput').click();state.photoTarget=r};$('#saveRecipe').onclick=async()=>{const title=$('#title').value.trim();if(!title){toast('Podaj nazwę przepisu');return}r.title=title;r.categoryId=$('#category').value;r.prepTime=$('#prepTime').value;r.cookTime=$('#cookTime').value;r.cookType=$('#cookType').value;r.servings=$('#servings').value;r.ingredients=[...document.querySelectorAll('#ingredients input')].map(x=>x.value.trim()).filter(Boolean);r.steps=[...document.querySelectorAll('#steps textarea')].map(x=>x.value.trim()).filter(Boolean);r.updatedAt=Date.now();await put('recipes',r);toast('Przepis zapisany!');route('detail',{id:r.id})}}
async function imageSelected(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{state.photoTarget.photo=reader.result;render()};reader.readAsDataURL(file)}
function bindSettings(){let drag=null;const list=$('#catList');list.querySelectorAll('.category-row').forEach(row=>{row.addEventListener('dragstart',()=>drag=row);row.addEventListener('dragover',e=>e.preventDefault());row.addEventListener('drop',e=>{e.preventDefault();if(drag&&drag!==row)list.insertBefore(drag,row)})});list.querySelectorAll('.delete-cat').forEach(b=>b.onclick=()=>b.parentElement.remove());$('#addCat').onclick=()=>{list.insertAdjacentHTML('beforeend',`<div class="category-row" draggable="true" data-id="${uid()}"><span class="handle">☷</span><input placeholder="Nazwa kategorii"><button class="mini-btn delete-cat">×</button></div>`);bindSettings()};$('#saveCats').onclick=async()=>{const rows=[...list.querySelectorAll('.category-row')];const existing=await cats();for(let i=0;i<rows.length;i++){const id=rows[i].dataset.id,name=rows[i].querySelector('input').value.trim();if(name)await put('categories',{id,name,order:i,icon:existing.find(x=>x.id===id)?.icon||icons[i%icons.length]})}for(const x of existing)if(!rows.some(r=>r.dataset.id===x.id))await del('categories',x.id);toast('Kategorie zapisane');render()};$('#export').onclick=async()=>{const data={app:'Pańcia gotuje',version:1,exportedAt:new Date().toISOString(),categories:await cats(),recipes:await recipes()};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`pancia-gotuje-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Kopia zapasowa została wyeksportowana')};$('#wake').onchange=e=>setWake(e.target.checked)}
async function setWake(on){state.keepScreen=on;if(!on){try{await state.wake?.release()}catch{}state.wake=null;toast('Automatyczne wygaszanie przywrócone');return}try{if('wakeLock'in navigator){state.wake=await navigator.wakeLock.request('screen');state.wake.addEventListener('release',()=>state.wake=null);toast('Ekran pozostanie aktywny podczas używania aplikacji')}else{toast('Ta wersja Safari nie obsługuje blokady wygaszania')}}catch{toast('Nie udało się włączyć blokady wygaszania')}}
$('#backBtn').onclick=()=>history.length>1?history.back():route('home');document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>route(b.dataset.route));$('#cameraInput').onchange=e=>imageSelected(e.target.files[0]);$('#galleryInput').onchange=e=>imageSelected(e.target.files[0]);document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'&&state.keepScreen&&'wakeLock'in navigator&&!state.wake){try{state.wake=await navigator.wakeLock.request('screen')}catch{}}});
async function init(){await openDB();render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js')}init();
